# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tunepid.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TunePID(object):
    def setupUi(self, TunePID):
        TunePID.setObjectName("TunePID")
        TunePID.resize(1272, 807)
        self.centralWidget = QtWidgets.QWidget(TunePID)
        self.centralWidget.setObjectName("centralWidget")
        self.p_save = QtWidgets.QPushButton(self.centralWidget)
        self.p_save.setGeometry(QtCore.QRect(210, 130, 80, 22))
        self.p_save.setObjectName("p_save")
        self.p_sim = QtWidgets.QWidget(self.centralWidget)
        self.p_sim.setGeometry(QtCore.QRect(29, 169, 531, 561))
        self.p_sim.setObjectName("p_sim")
        self.p_Kp_slider = QtWidgets.QSlider(self.centralWidget)
        self.p_Kp_slider.setGeometry(QtCore.QRect(50, 60, 471, 21))
        self.p_Kp_slider.setMaximum(1000)
        self.p_Kp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.p_Kp_slider.setObjectName("p_Kp_slider")
        self.axes_list = QtWidgets.QComboBox(self.centralWidget)
        self.axes_list.setGeometry(QtCore.QRect(490, 20, 79, 22))
        self.axes_list.setObjectName("axes_list")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.label.setObjectName("label")
        self.p_Kp = QtWidgets.QLabel(self.centralWidget)
        self.p_Kp.setGeometry(QtCore.QRect(530, 60, 59, 14))
        self.p_Kp.setObjectName("p_Kp")
        self.v_sim = QtWidgets.QWidget(self.centralWidget)
        self.v_sim.setGeometry(QtCore.QRect(610, 170, 531, 561))
        self.v_sim.setObjectName("v_sim")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 31, 16))
        self.label_2.setObjectName("label_2")
        self.p_Ki_slider = QtWidgets.QSlider(self.centralWidget)
        self.p_Ki_slider.setGeometry(QtCore.QRect(50, 80, 471, 21))
        self.p_Ki_slider.setMaximum(1000)
        self.p_Ki_slider.setOrientation(QtCore.Qt.Horizontal)
        self.p_Ki_slider.setObjectName("p_Ki_slider")
        self.p_Ki = QtWidgets.QLabel(self.centralWidget)
        self.p_Ki.setGeometry(QtCore.QRect(530, 80, 59, 14))
        self.p_Ki.setObjectName("p_Ki")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 31, 16))
        self.label_3.setObjectName("label_3")
        self.p_Kd_slider = QtWidgets.QSlider(self.centralWidget)
        self.p_Kd_slider.setGeometry(QtCore.QRect(50, 100, 471, 21))
        self.p_Kd_slider.setMaximum(1000)
        self.p_Kd_slider.setOrientation(QtCore.Qt.Horizontal)
        self.p_Kd_slider.setObjectName("p_Kd_slider")
        self.p_Kd = QtWidgets.QLabel(self.centralWidget)
        self.p_Kd.setGeometry(QtCore.QRect(530, 100, 59, 14))
        self.p_Kd.setObjectName("p_Kd")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(600, 60, 31, 16))
        self.label_4.setObjectName("label_4")
        self.v_Ki = QtWidgets.QLabel(self.centralWidget)
        self.v_Ki.setGeometry(QtCore.QRect(1120, 80, 59, 14))
        self.v_Ki.setObjectName("v_Ki")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(600, 100, 31, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(600, 80, 31, 16))
        self.label_6.setObjectName("label_6")
        self.v_Kp_slider = QtWidgets.QSlider(self.centralWidget)
        self.v_Kp_slider.setGeometry(QtCore.QRect(640, 60, 471, 21))
        self.v_Kp_slider.setMaximum(1000)
        self.v_Kp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.v_Kp_slider.setObjectName("v_Kp_slider")
        self.v_Ki_slider = QtWidgets.QSlider(self.centralWidget)
        self.v_Ki_slider.setGeometry(QtCore.QRect(640, 80, 471, 21))
        self.v_Ki_slider.setMaximum(1000)
        self.v_Ki_slider.setOrientation(QtCore.Qt.Horizontal)
        self.v_Ki_slider.setObjectName("v_Ki_slider")
        self.v_Kp = QtWidgets.QLabel(self.centralWidget)
        self.v_Kp.setGeometry(QtCore.QRect(1120, 60, 59, 14))
        self.v_Kp.setObjectName("v_Kp")
        self.v_Kd_slider = QtWidgets.QSlider(self.centralWidget)
        self.v_Kd_slider.setGeometry(QtCore.QRect(640, 100, 471, 21))
        self.v_Kd_slider.setMaximum(1000)
        self.v_Kd_slider.setOrientation(QtCore.Qt.Horizontal)
        self.v_Kd_slider.setObjectName("v_Kd_slider")
        self.v_Kd = QtWidgets.QLabel(self.centralWidget)
        self.v_Kd.setGeometry(QtCore.QRect(1120, 100, 59, 14))
        self.v_Kd.setObjectName("v_Kd")
        self.save_gains_2 = QtWidgets.QPushButton(self.centralWidget)
        self.save_gains_2.setGeometry(QtCore.QRect(670, 20, 80, 22))
        self.save_gains_2.setObjectName("save_gains_2")
        self.v_save = QtWidgets.QPushButton(self.centralWidget)
        self.v_save.setGeometry(QtCore.QRect(810, 130, 80, 22))
        self.v_save.setObjectName("v_save")
        self.p_cascaded = QtWidgets.QCheckBox(self.centralWidget)
        self.p_cascaded.setGeometry(QtCore.QRect(350, 130, 131, 20))
        self.p_cascaded.setObjectName("p_cascaded")
        TunePID.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(TunePID)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1272, 19))
        self.menuBar.setObjectName("menuBar")
        TunePID.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(TunePID)
        self.mainToolBar.setObjectName("mainToolBar")
        TunePID.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(TunePID)
        self.statusBar.setObjectName("statusBar")
        TunePID.setStatusBar(self.statusBar)

        self.retranslateUi(TunePID)
        QtCore.QMetaObject.connectSlotsByName(TunePID)

    def retranslateUi(self, TunePID):
        _translate = QtCore.QCoreApplication.translate
        TunePID.setWindowTitle(_translate("TunePID", "TunePID"))
        self.p_save.setText(_translate("TunePID", "Save gains"))
        self.label.setText(_translate("TunePID", "Kp"))
        self.p_Kp.setText(_translate("TunePID", "0"))
        self.label_2.setText(_translate("TunePID", "Ki"))
        self.p_Ki.setText(_translate("TunePID", "0"))
        self.label_3.setText(_translate("TunePID", "Kd"))
        self.p_Kd.setText(_translate("TunePID", "0"))
        self.label_4.setText(_translate("TunePID", "Kp"))
        self.v_Ki.setText(_translate("TunePID", "0"))
        self.label_5.setText(_translate("TunePID", "Kd"))
        self.label_6.setText(_translate("TunePID", "Ki"))
        self.v_Kp.setText(_translate("TunePID", "0"))
        self.v_Kd.setText(_translate("TunePID", "0"))
        self.save_gains_2.setText(_translate("TunePID", "Save file"))
        self.v_save.setText(_translate("TunePID", "Save gains"))
        self.p_cascaded.setText(_translate("TunePID", "Cascaded position"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TunePID = QtWidgets.QMainWindow()
    ui = Ui_TunePID()
    ui.setupUi(TunePID)
    TunePID.show()
    sys.exit(app.exec_())

